#PlatformDev：shandong
#PlatformTest: beijing

currentEnv: PlatformTest

thread:
    thread_num : 4

flask:
    host: "0.0.0.0"
    port: 8383
    api: '/api/rcaService'

env:
  PlatformTest:
      mysql_host: '10.10.27.130'
      mysql_user: 'root'
      mysql_passwd: 'hpnl123456'
      mysql_database: 'aiops'

      es_ip: '10.10.26.43'
      es_index: 'anomaly-result-2019.12.25-test-method'


  PlatformDev:
      mysql_host: '10.10.27.130'
      mysql_user: 'root'
      mysql_passwd: 'hpnl123456'
      mysql_database: 'aiops'

      es_ip: '10.10.26.43'
      es_index: 'anomaly-result-2019.12.25-test-method'

