#PlatformDev：shandong
#PlatformTest: beijing

currentEnv: PlatformDev

thread:
    thread_num : 50

flask:
    host: "0.0.0.0"
    port: 8383
    api: '/api/rcaService'

env:
  PlatformTest:
      mysql_host: '10.10.27.130'
      mysql_user: 'root'
      mysql_passwd: 'hpnl123456'
      mysql_database: 'aiops'
      
      es_ip: '10.10.26.43'
      es_index: 'anomaly-result-2019.12.25-final'

  PlatformDev:
      mysql_host: '39.137.77.247'
      mysql_user: 'root'
      mysql_passwd: '123456'
      mysql_database: 'aiops'

      es_ip: '39.137.77.247'
      es_index: 'iie-aiops-location-ad'
